#+hugo_base_dir: ../
#+hugo_front_matter_format: yaml
#+seq_todo: TODO DRAFT DONE
#+options: author:nil
#+startup: overview

* Instructions
=C-c C-e H H=
=M-x hhyu-hugo-insert-post=
=M-x hhyu-hugo-insert-image=
=#+attr_html: :width 300px :class center=

* Micros
** DONE Micro: Which Hinton?
CLOSED: [2025-12-10 Wed 21:20]
:PROPERTIES:
:EXPORT_FILE_NAME: 202512102106_micro-which-hinton
:EXPORT_HUGO_SECTION: micro
:EXPORT_HUGO_TAGS: "Jorge Luis Borges" "math" 
:EXPORT_DATE: CLOSED
:END:
In /Tlön, Uqbar, Orbis Tertius/, Borges discovered an important clue to toe secrets of /Tlön/ when he found a letter hidden in a book:

#+begin_quote
In March of 1941, a handwritten letter from Gunnar Erfjord was discovered in a book by Hinton that had belonged to Herbert Ashe.
#+end_quote

Gunnar Erfjord and Herber Ashe are both fictional characters who are members of the /Orbis Tertius/ secret society, but who is Hinton? Hinton is mentioned only once in the entire story, so he must be a historical figure. But which Hiton is so famous that he could be referred to just by the last name?

Interestingly, it is the mathematician [[https://en.wikipedia.org/wiki/Charles_Howard_Hinton][Charles Howard Hintin]], whose fictional and non-fictional writings had inspired the public's interest in the fourth dimension. He was name-checked in two other stories by Borges (/The Secret Miracle/ and /There Are More Things/), and was mentioned by H.P. Lovecraft and Aleister Crowley.
** DONE Micro: Why so much interest in the longitude in the 1990's?
CLOSED: [2026-03-09 Mon 17:59]
:PROPERTIES:
:EXPORT_FILE_NAME: 202603091756_micro-why-so-much-interest-in-the-longitude-in-the-1990-s
:EXPORT_HUGO_SECTION: micro
:EXPORT_HUGO_TAGS: "Thomas Pynchon" "Umberto Eco" "book" "Science"
:EXPORT_DATE: CLOSED
:END:
Why so much interest in the longitude in the 1990’s?

- The Island of the Day Before (Umberto Eco, 1994): A novel set in the middle 17th century, when European started to tackle the problem of measuring longitude at sea. 
- Longitude (Dava Sobel, 1995): A non-fictional book about the history of the longitude problem.
- Mason & Dixon (Thomas Pynchon, 1997): A novel with numerous references to the longitude problem, set at a time when the problem was just solved (about 100 years after Eco’s novel)
** DONE Micro: The meaning of percussion
CLOSED: [2026-03-09 Mon 18:21]
:PROPERTIES:
:EXPORT_FILE_NAME: 202603091803_micro-the-meaning-of-percussion
:EXPORT_HUGO_SECTION: micro
:EXPORT_HUGO_TAGS: "music" "gamelan" 
:EXPORT_DATE: CLOSED
:END:
I love [[https://www.youtube.com/watch?v=-lkAOZC1w3g][this]] lecture by UCSD's music professor Steven Schick about percussion music.  He said that in music, the suffix /ist/ is focused on the object that is played. For example, in the word /pianist/, the focus is on the piano.  The term /percussionis/, however, is not centered on an instrument. Rather, it is centered on what the musician does. The German word for percussion /schlagzeug/ defines the music perfectly: /schlag/ means to "strike" and /zeug/ means "stuff". That's what percussionists do: they strike stuff.

Interestingly I recently the word /gamelan/ also refers to an action. The word is derived from the Javanese word /gamel/, which means "to handle". The same word also refers to a type of hammer. So the word /gamelan/ is also related to the act of hitting the instrument with a mallet.
** DONE Micro: Why did AI make this mistake?
CLOSED: [2026-05-25 Mon 20:46]
:PROPERTIES:
:EXPORT_FILE_NAME: 202605252019_micro-why-did-ai-make-this-mistake
:EXPORT_HUGO_SECTION: micro
:EXPORT_HUGO_TAGS: "gamelan" "history" "AI"
:EXPORT_DATE: CLOSED
:END:
According to a certain AI service, the 1900 Paris Expo (i.e. [[https://en.wikipedia.org/wiki/Exposition_Universelle_(1900)][Exposition Universelle]]) featured gamelans from Surakarta (central Java) and /Bali/.  That sounded very unlikely, because the first Balinese gamelan performance in Europe, I read, was by _Gunung Sari of Peliatan_ in the 1931 [[https://en.wikipedia.org/wiki/Paris_Colonial_Exposition][Paris Colonial Exposition]].  Where did the AI get the idea from? One possibility is that Judith Gautier, the 19th century Parisian writer, wrote that the gamelan musicians who graced the 1900 Paris Expo were from "Solo, Bali".  That was clearly an error, but now it might find its way into someone's homework.  Interestingly, that performance was attended by Olivier Messiaen. 


