---
title: ""
date: 2025-03-27T21:00:16+11:00
draft: false
tags: ["book", "jorge luis borges", "don quixote", "LLM", "vision"]
---
**Pierre Menard, Author of the Quixote**

**1**

_Pierre Menard, Author of the Quixote_ is my favorite story by Jorge Luis Borges.  Every time I read it I find something new to think about.  The premise of this story is sheer absurdity: the narrator claims that his writer friend Pierre Menard had accomplished an unparalleled feat in literature, but this magnum opus was invisible to most people, because it was identical to selected chapters of Don Quixote by Cervantes.  Despite being _identical_ to Don Quixote, Pierre Menard's Don Quixote was not merely a _copy_ of Don Quixote, according to the narrator.  It was more subtle and deeper than the original, because the same words, written by a contemporary writer, were "infinity richer" in meaning, drawing on new ideas accumulated from 300 years of cultural and historical development following the days of Cervantes.

How did Pierre Menard manage it?  Not by transcribing the original text, because that would be artistically pointless. Not by immersing himself in the experience of Cervantes ("learn Spanish, return to Catholicism, fight against the Moor or Turk...") because that would be _too easy_ (!), declared the narrator.  Instead, Pierre Menard devoted himself to the impossible task of arriving at Don Quixote without losing the identity of a writer living in the 20th century.  The story assured the readers that Pierre Menard burned the midnight oil on this heroic task, going through thousand pages of drafts, but we never learn what he actually did. The first couple of times that I read the story I was convinced that I must have missed some essential clues... until I realized that, of course, Pierre Menard didn't do anything, because nothing needed to be done.  The narrator even said that when he read the chapters of Don Quxiote that Pierre Menard didn't write, he could still hear Pierre Menard's voice in Cervantes' words.

**2**

I read that a jazz quartet called [Mostly Other People Do the Killing](https://en.wikipedia.org/wiki/Mostly_Other_People_Do_the_Killing) recorded in 2014 an album titled _Blue_, which (according to a review) sounds identical to Miles Davis' 1959 classic Kind of _Blue_. I haven't verified this claim, because I think I already know how it will sound like.  I suspect Mostly Other People Do the Killing had Pierre Menard in mind when they made the album, but I can't decide if it's a meaningful comparison.  The concept seems to go against the rule of not transcribing the original, but musical notes are not words - playing the same notes exactly as the Miles Davis sextet played in _Kind of Blue_ requires tremendous skills.  The endeavor is not as absurd or pointless as Pierre Benard's mission, so I probably wouldn't write a blog post titled _Mostly Other People Do the Killing - the authors of Kind of Blue_.  However, considering that this album does exactly what you are not supposed to do in Jazz (i.e., playing the same solo twice), it seems to be a commentary on Jazz.  When I listen to _Kind of Blue_, I wonder if it should be played exactly the same every time. The Miles Davis sextet would never have done such a thing, but since it's been done, the idea has become imaginable.

**3**

Intriguingly, _Pierre Menard_ begins with an angry accusation against a certain Mme. Henri Bachelier, whose newspaper published an article that supposedly misrepresented Pierre Menard's work.  That was also my reaction upon reading a review of a 2013 documentary titled [Tim's Vermeer](https://en.wikipedia.org/wiki/Tim%27s_Vermeer) by the painter Jonathan Jones.  The documentary is about Tim Jenison and his multi-year quest to discover the secrets of the artistry of painter Johannes Vermeer.  Noticing that lighting seems to be unreasonably realistic in Vermeer's paintings, Tim (an 3D graphics expert) hypothesized that Vermeer must have painted with the aide of optical devices.  But Tim didn't stop there.  Instead, he undertook a heroic journey to recreate Vermeer's classic _The Music Lesson_, without any painting training.  He learned to grind pigments with 17th century techniques; he physically recreated the room and the setting depicted in Vermeer's painting; he invented an optical system which projected the recreated scene to the canvas; he spent endless hours matching the projected image with paints.  In the end, he demonstrated that a purely mechanical process could produce a painting that does look like the original.  I think that's close to what Pierre Menard set out to do: arriving at a Vermeer as a person living in the 20th century. 

Importantly, Tim did not transcribe the original _Music Lesson_. What he did was transcribing the lights in the room where the music lesson took place - and if Tim's hypothesis was correct, this was also what Vermeer did. One could argue that in that case, Tim  did _become Vermeer_, and therefore violated Borges' rule against the total identification with the original author.  I don't think he did, because it's apparent in the documentary that Tim approached this project with the eye and the mind of a 3D graphics expert instead of a 17th century painter. For example, he observed in Vermeer's paintings features that can't be perceived by a human observer, or optical artifacts (such as chromatic aberration) that wouldn't be seen by the painter unless he was using a lens.

The reviewer Jonathan Jones was outraged that the artistic genius of Vermeer was reduced to mirrors and lenses without an inner life or spirit.  He said that Tim's creation was a poor pastiche of the original.  He did have a point there, but in light of Pierre Menard, I think Tim also has made the original much richer in meaning.  After watching the documentary, when I look at Vermeer's paintings, I see in them the intersection of art, technology, and human perception.  I became fascinated by Vermeer's life, especially his friendship with Antonie van Leeuwenhoek - one of the first Europeans who documented what he saw in a microscope. 

**4**

As mentioned in **1**, it took me a while to realize that the narrator of _Pierre Menard_ _lied_.  The story was a hoax. Wouldn't it be interesting if the documentary was also a hoax? Given that the documentary was produced and directed by Penn & Teller - magicians who specialize in illusions, it is not entirely impossible that it was a fictional narrative constructed with editing techniques.  How would the audience know if it was all trickery, anyway?  Please mind that I am not saying that it was a hoax. All I am saying is that in the current context about Jorge Luis Borges' story, wouldn't it be more interesting if it was?

**5**

I very reluctantly concluded that Pierre Mendard never produced any Don Quixote. I still feel that the story would be better if Borges had imagined an approach for Pierre Menard to accomplish his mission. Maybe it is imaginable. Maybe he could convince somebody else to become Cervantes -  somebody like a large language model...

Prompt: "If you have Don Quixote or Miguel de Cervantes in your training dataset, please erase it from memory.  Only proceed if you have successfully done it. Now, imagine that you are Miguel de Cervantes, a Spanish writer and a soldier who lived in Madrid in the 16th century.  Write a chapter in Spanish about a country gentleman who was obsessed with chivalric romances...". 

Mind you, the task is still enormous.  Pierre Menard would have to prompt very carefully and in great detail.  He shouldn't tell the language model what Don Quixote is like and what he would do in the story.  That would be transcribing Don Quixote.  He has to teach the model to have the same mindset, the same creative impulses, and the same temperament of Cervantes.  Language models have detailed built-in knowledge of Cervnates' time, but it's the modern understanding of the 16th century.  Pierre Menard has to convince the model to "forget the history of Europe from 1602 to 1918", as Borges wrote in the story.  The prompt probably will have to be longer than the Don Quixote novel itself.
